export default {
  "login": "Michael9905",
  "id": 161143403,
  "node_id": "U_kgDOCZraaw",
  "avatar_url": "https://avatars.githubusercontent.com/u/161143403?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Michael9905",
  "html_url": "https://github.com/Michael9905",
  "followers_url": "https://api.github.com/users/Michael9905/followers",
  "following_url": "https://api.github.com/users/Michael9905/following{/other_user}",
  "gists_url": "https://api.github.com/users/Michael9905/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Michael9905/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Michael9905/subscriptions",
  "organizations_url": "https://api.github.com/users/Michael9905/orgs",
  "repos_url": "https://api.github.com/users/Michael9905/repos",
  "events_url": "https://api.github.com/users/Michael9905/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Michael9905/received_events",
  "type": "User",
  "user_view_type": "public",
  "site_admin": false,
  "name": "Michael B.",
  "company": "Web/Software Developer",
  "blog": "https://michaelbasazinew.com/portfolio/",
  "location": "Herndon",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 6,
  "public_gists": 0,
  "followers": 0,
  "following": 3,
  "created_at": "2024-02-24T15:01:46Z",
  "updated_at": "2025-03-11T16:35:26Z"
}